export const EMPTY_CARD = {
    collection_id: "",
    league: "",
    team: "",
    player: "",
    position: "",
    rookie: false,
    relic: false,
    autograph: false,
    inserts: "",
    parallel: "",
    brand: "",
    yeardate: "",
    set_name: "",
    set_number: "",
    rarity: "",
    price: "",
    front_image: "",
    back_image: "",
}

export const CARD_MODAL_DATA = {
    player: { type: "Input", label: "Player", placeholder: "Enter the name of the Athlete" },
    position: { type: "Input", label: "Position", placeholder: "Enter the name of their position" },
    rookie: { type: "Checkbox", label: "Rookie" },
    relic: { type: "Checkbox", label: "Relic" },
    autograph: { type: "Checkbox", label: "Autograph" },
    inserts: { type: "Input", label: "Insert", placeholder: "Insert?" },
    parallel: { type: "Input", label: "Parallel", placeholder: "Parallel?" },
    brand: { type: "Input", label: "Card Brand", placeholder: "Enter the brand" },
    yeardate: { type: "Input", label: "Year of release", placeholder: "What year card?", inputType: "number" },
    set_name: { type: "Input", label: "Card Set", placeholder: "Enter the name of the Set" },
    set_number: { type: "Input", label: "Card Name", placeholder: "What number card is it?", inputType: "number" },
    rarity: { type: "Input", label: "Rarity of card", placeholder: "How rare? 1/x", inputType: "number" },
    price: { type: "Input", label: "Price of card (USD)", placeholder: "Price?", inputType: "number" }
};


export const LEAGUE_DATA = [
    {
        league: "MLB",
        teams: [
            "Arizona Diamondbacks",
            "Atlanta Braves",
            "Baltimore Orioles",
            "Boston Red Sox",
            "Chicago White Sox",
            "Chicago Cubs",
            "Cincinnati Reds",
            "Cleveland Guardians",
            "Colorado Rockies",
            "Detroit Tigers",
            "Houston Astros",
            "Kansas City Royals",
            "Los Angeles Angels",
            "Los Angeles Dodgers",
            "Miami Marlins",
            "Milwaukee Brewers",
            "Minnesota Twins",
            "New York Yankees",
            "New York Mets",
            "Oakland Athletics",
            "Philadelphia Phillies",
            "Pittsburgh Pirates",
            "San Diego Padres",
            "San Francisco Giants",
            "Seattle Mariners",
            "St. Louis Cardinals",
            "Tampa Bay Rays",
            "Texas Rangers",
            "Toronto Blue Jays",
            "Washington Nationals"
        ]
    },
    {
        league: "NBA",
        teams: [
            "Atlanta Hawks",
            "Boston Celtics",
            "Brooklyn Nets",
            "Charlotte Hornets",
            "Chicago Bulls",
            "Cleveland Cavaliers",
            "Dallas Mavericks",
            "Denver Nuggets",
            "Detroit Pistons",
            "Golden State Warriors",
            "Houston Rockets",
            "Indiana Pacers",
            "Los Angeles Clippers",
            "Los Angeles Lakers",
            "Memphis Grizzlies",
            "Miami Heat",
            "Milwaukee Bucks",
            "Minnesota Timberwolves",
            "New Orleans Pelicans",
            "New York Knicks",
            "Oklahoma City Thunder",
            "Orlando Magic",
            "Philadelphia 76ers",
            "Phoenix Suns",
            "Portland Trail Blazers",
            "Sacramento Kings",
            "San Antonio Spurs",
            "Toronto Raptors",
            "Utah Jazz",
            "Washington Wizards"
        ]
    },
    {
        league: "NHL",
        teams: [
            "Anaheim Ducks",
            "Arizona Coyotes",
            "Boston Bruins",
            "Buffalo Sabres",
            "Calgary Flames",
            "Carolina Hurricanes",
            "Chicago Blackhawks",
            "Colorado Avalanche",
            "Columbus Blue Jackets",
            "Dallas Stars",
            "Detroit Red Wings",
            "Edmonton Oilers",
            "Florida Panthers",
            "Los Angeles Kings",
            "Minnesota Wild",
            "Montreal Canadiens",
            "Nashville Predators",
            "New Jersey Devils",
            "New York Islanders",
            "New York Rangers",
            "Ottawa Senators",
            "Philadelphia Flyers",
            "Pittsburgh Penguins",
            "San Jose Sharks",
            "Seattle Kraken",
            "St. Louis Blues",
            "Tampa Bay Lightning",
            "Toronto Maple Leafs",
            "Vancouver Canucks",
            "Vegas Golden Knights",
            "Washington Capitals",
            "Winnipeg Jets"
        ]
    },
    {
        league: "Premier League",
        teams: [
            "Arsenal",
            "Aston Villa",
            "Bournemouth",
            "Brentford",
            "Brighton & Hove Albion",
            "Burnley",
            "Chelsea",
            "Crystal Palace",
            "Everton",
            "Fulham",
            "Liverpool",
            "Luton Town",
            "Manchester City",
            "Manchester United",
            "Newcastle United",
            "Nottingham Forest",
            "Sheffield United",
            "Tottenham Hotspur",
            "West Ham United",
            "Wolverhampton Wanderers"
        ]
    }
];

